# visit https://github.com for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: EdgeBoy
google_analytics: EdgeBoy
<<<<<<< HEAD
title: www.edgeboy.cn
=======
title: 欢迎光临访问本小站^_^ ！
>>>>>>> 4edf39ce374d0d85da4af9031d0b5279be198670
summary: Programming is an Art.

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
<<<<<<< HEAD
      title: www.edgeboy.cn
=======
      title: 欢迎光临访问本小站^_^ ！
>>>>>>> 4edf39ce374d0d85da4af9031d0b5279be198670
summary: Programming is an Art.
description: Stylish Jekyll Theme
author:
  name: EdgeBoy
  email: yl005512@163.com
  github: EdgeBoy
  QQ: 949068284
  weibo: furinkazan00
  OSC: edgeboy
  bio: 生活是一场修行！
  summary: Programming is an Art.
rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate
